[package]
name = "ring_api"
version = "0.1.0"
authors = ["Árpád Goretity <h2co3@h2co3.org>"]
edition = "2018"

[dependencies]
reqwest = "0.9.17"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = "1.1.7"
lazy_static = "1.3.0"
